### ISSUE TITLE
Sprint 6

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico#18]
Objetivos
- [ ] Finalizar a aplicação WEB-APP e publicar a solução nos ambientes de homologação e produção

Resultados chaves:
- [ ] Banco de dados copiado em produção (estrutura e dados dos bancos Organograma e ProcessoEletronico)
- [ ] Criação da API no ambiente de produção
- [ ] Quarta-feira ter a versão publicada em produção
