### ISSUE TITLE
Sprint 7

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico#28]
Objetivos
- [x] Desenvolver os CRUDs de Organização do Organograma e Plano de Classificação do Processo Eletrônico (aplicações WEB-APP) e publicar a manutenções nos ambientes de homologação e produção

Resultados chaves:
- [ ] Aplicação Organograma com o 1º CRUD disponível
- [x] Plano de Classificação disponível para uso pelos gestpres no ambiente de desenvolvimento e homologação para testes.
