### ISSUE TITLE
Sprint 8

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico#29]
Objetivos
- [x] Desenvolver os CRUDs de Unidade do Organograma, publicar em produção a atualização do Processo Eletrônico (aplicações WEB-APP) contendo CRUD de Plano de Classificação

Resultados chaves:
- [x] Aplicação Organograma com o 1º CRUD (desenvolvimento)
- [x] Aplicação Processo Eletrônico testada com o Plano de Classificação disponível.
- [ ] Publicação em produção de uma nova versão do Processo Eletrônico, incluindo número de versão.
