### ISSUE TITLE
Sprint 9

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico#30]
Objetivos
- [x] Desenvolver os CRUDs de Organização do Organograma (API e APP), publicar em produção a atualização do Processo Eletrônico (aplicações WEB-APP) contendo CRUD de Plano de Classificação, juntamente com a versão demonstração.

Resultados chaves:
- [ ] Aplicação Organograma com o 2º CRUD disponível no ambiente de produção.
- [x] Aplicação Processo Eletrônico testada com o Plano de Classificação disponível.
- [x] Aplicação Processo Eletrônico Demostração.
- [x] Publicação no Git de branch do Processo Eletrônico, incluindo número de versão.
