### ISSUE TITLE
Sprint 10

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico#31]
Objetivos
- [x] Publicar aplicação de Organograma testada no ambiente de produção, juntamente com a migração dos dados do Organograma..

Resultados chaves:
- [x] Aplicação Organograma publicada em produção.
- [ ] Finalização do desenvolvimento do rascunho do processo.
- [x] Migração dos dados do Organograma.
