### ISSUE TITLE
Sprint 11

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico#32]
Objetivos
- [ ] Implementar funcionalidade de racunho de processo completo, permitindo as funções de edição, insersão, busca e exclusão de todos os subrecursos associados. 
- [ ] Implementar Autuação de processo através de um rascunho.
- [x] Automatização da integração com o SIARHES;
- [ ] Correção dos erros na aplicação do Organograma (WebApp)

Resultados chaves:
