### ISSUE TITLE
Sprint 12

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico#33]
Objetivos
- [x] Atualizar versão 3.0 do Processo Eletrônico em produção

Resultados chaves:
- [ ]  Camada de aplicação do Processo Eletrônico refatorada
- [x]  Controle de auditoria e histórico do Sistema de Organograma implantado 
- [x]  Notificações aos usuários e interessados do processo implantada
- [x] Funcionalidade de racunho de processo completo, permitindo as funções de edição, insersão, busca e exclusão de todos os subrecursos associados na Camada WebApp implementada;
- [x] Correção dos erros na aplicação do Organograma (WebApp)
