### ISSUE TITLE
Sprint 1

### ISSUE THREAD

**Issue by fontourafernando** [prodest/processo-eletronico#4]
Objetivos - Aumente suas chances de chegar aonde você quer, definindo onde você quer estar.

Um bom objetivo de Sprint deve ser específico e mensurável, ajudando o time a ter um propósito comum.
- Documentar qual será e como será implementada a configuração do projeto de forma que qualquer outro servidor (funcionário) possa segui-lo e conseguir começar a trabalhar no projeto.

Entregáveis - O que será entregue nessa Sprint. Usando o markup do GitHub nós conseguimos listar e acompanhar facilmente cada situação.
- [x] #1 - Documentar configuração do projeto
- [x] #2 - Estrutura da solução Web API no repositório
- [x] #3 - Estrutura da solução Web App no repositório

Métricas e Critérios - Quanto tempo a Sprint vai durar e quais são os critérios de aceitação? Incluindo essa informação fica fácil analisá-la futuramente.

A Sprint vai durar 1 semana e será considerada um sucesso caso:
- [x] Documento criado
- [x] Primeira versão da estrutura da solução Web API dentro de seu repositório.
- [ ] Primeira versão da estrutura da solução Web App dentro de seu repositório.
