### ISSUE TITLE
Sprint 13

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico#46]
Objetivos
- [ ] Desenvolver APIs de Pendência e Sinalização do processo eletrônico e começar o desenvolvimento do Sistema de Classificação Documental.

Resultados chaves:
- [ ]  API de Pendência implementado 
- [x]  API de Sinalização implementado 
- [x] API de refatoração do Plano de Classificação Documental implementado.
