### ISSUE TITLE
Sprint 14

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico#47]
Objetivos
- [ ] Concluir o desenvolvimento  do plano de classificação Documental e Bloqueio de Processo.

Resultados chaves:
- [x]  plano de aplicação documental implementado
- [x]  entregar a funcionalidade de bloqueio do despacho
- [x]  entregar a funcionalidade de Plano de Classificação
- [ ]  entregar a funcionalidade de Nível de Classificação
- [ ]  entregar a funcionalidade de Tipo Documental
