### ISSUE TITLE
Sprint 15

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico#48]
Objetivos
- [x] Desenvolver Atividades e Tipos documentais do sistema de classificação documental. Concluir refatoração da camada de web-app do Processo Eletrônico.

Resultados chaves:
- [x]  Camada web-app refatorada e  pronta para criação de novos recursos
- [x]  EU039 e EU040 entregues.
