### ISSUE TITLE
Sprint 16

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico#50]
Objetivos
- [x] Desenvolver Tipos documentais e Tabela de Sigilo Documental. Para o Processo Eletrônico, entregar o rascunho de despachos.

Resultados chaves:
- [x]  Versão do Sistema de Classificação documental em homologação, com as estórias EU038, EU039, EU040, EU041 e EU043
- [ ]  Processo Eletrônico com recurso de rascunho de despacho desenvolvido e no ambiente de homologação.
