### ISSUE TITLE
Sprint 1

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico#7]
Objetivos
- [ ] Consumir serviços do Organograma, já com as telas prontas
- [ ] Desenvolvimento da API de Autuar Processo
- [ ] Aplicação dos templates das telas da aplicação de Processo Eletrônico

Métricas e Critérios:
A Sprint vai durar 1 semana e será considerada um sucesso caso:
- Se tivermos as telas do Processo Eletrônico desenhadas, já consumindo o serviço de Autenticação e, também, os serviços de Organograma.
