### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by viniciusgazzoli** [prodest/processo-eletronico#8]
Objetivos
- [ ] Uma versão do documento de especificação das Estória de Usuário
- [ ] Construção dos serviços de Consultas das informações auxiliares necessárias para autuação do processo.
- [ ] # Versão 0.2 da tela de autuação de processo.

Métricas e Critérios:
A Sprint vai durar 1 semana e será considerada um sucesso caso:
-
